[platformio]
default_envs = esp32-s3-n16r8

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    SPI
    https://github.com/lvgl/lvgl/archive/refs/tags/v8.3.11.zip
    https://github.com/mikalhart/TinyGPSPlus/archive/refs/heads/master.zip

[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

board_build.extra_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

build_flags =
    -I"src"
    -DLV_CONF_INCLUDE_SIMPLE
    -DBOROVIK_BOARD_DEVKITC_S3

upload_port = COM5
monitor_port = COM5

[env:freenove-wrover-cam-mvp]
board = esp-wrover-kit
board_build.partitions = huge_app.csv
board_build.flash_mode = dio
board_build.f_cpu = 240000000L
board_build.f_flash = 40000000L
build_flags =
    -I"src"
    -DLV_CONF_INCLUDE_SIMPLE
    -DBOARD_HAS_PSRAM
    -DBOROVIK_BOARD_FREENOVE_WROVER_CAM_MVP
upload_port = COM6
monitor_port = COM6
upload_speed = 115200
