[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

board_build.extra_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; TFT_eSPI — конфиг дисплея ST7789 2.4" 240x320 через build_flags
build_flags =
    -DUSER_SETUP_LOADED
    -DST7789_DRIVER
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=8
    -DTFT_DC=9
    -DTFT_RST=10
    -DTFT_BL=-1
    -DSPI_FREQUENCY=27000000
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4
    -DLOAD_GFXFF
    -DSMOOTH_FONT

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    mikalhart/TinyGPSPlus
    bodmer/TFT_eSPI
